spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/ainidewowjf/springcloudConfig
          searchPaths: src/respo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/